baseURL = "http://bigtop.apache.org/"
languageCode = "en-us"
title = "Apache Bigtop"
theme = "ananke"

[params]
    custom_css = ["css/mine.css"]
    background_color_class = "bg-dark-red"
    featured_image = "/images/bigtop-logo3.png"